// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package sqlc

import (
	"context"
)

const insertWord = `-- name: InsertWord :exec
INSERT INTO word (name) VALUES ($1)
ON CONFLICT (name) DO NOTHING
`

func (q *Queries) InsertWord(ctx context.Context, db DBTX, name string) error {
	_, err := db.Exec(ctx, insertWord, name)
	return err
}

const insertWordSymbol = `-- name: InsertWordSymbol :exec
INSERT INTO word_symbol (word, pronunciation_num, position, symbol)
VALUES ($1, $2, $3, $4)
`

type InsertWordSymbolParams struct {
	Word             string
	PronunciationNum int16
	Position         int16
	Symbol           string
}

func (q *Queries) InsertWordSymbol(ctx context.Context, db DBTX, arg InsertWordSymbolParams) error {
	_, err := db.Exec(ctx, insertWordSymbol,
		arg.Word,
		arg.PronunciationNum,
		arg.Position,
		arg.Symbol,
	)
	return err
}
